name: Update Playlist

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.NODEJS }}
      GH_USERNAME: rafkichanel
      GH_REPO: My-IPTV

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install axios simple-git

      - name: Run update_playlist.js
        run: node scripts/update_playlist.js
